version: '2'

services:
  certbot:
    build: ./nginx
    container_name: certbot
    links:
      - app:${DOMAIN_NAME}
    ports:
      - 80:80/tcp
      - 443:443/tcp
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=email@company.com
      - DOMAIN_NAME=company.com
  ${APP_NAME}:
    build: ./${APP_NAME}
    container_name: ${APP_NAME}
    restart: always
